"use client";
import { useEffect,useState } from "react";
import { useLocale } from "@/lib/locale-context";
const key="osint-evidence-note-v1";
const empty={question:"",source:"",accessed:"",observation:"",limits:"",conclusion:"",next:""};
export default function EvidenceNotebook({suggestedQuestion}: {suggestedQuestion?: string}){
 const {locale}=useLocale(); const zh=locale==="zh-TW"; const [note,setNote]=useState(empty); const [ready,setReady]=useState(false); const [status,setStatus]=useState("");
 useEffect(()=>{try {const raw=localStorage.getItem(key);if(raw){const saved=JSON.parse(raw);setNote(Object.fromEntries(Object.entries(empty).map(([k,v])=>[k,typeof saved?.[k]==="string"?saved[k]:v])) as typeof empty);}}catch{setStatus("Local storage unavailable / 無法讀取本機儲存");}setReady(true);},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(key,JSON.stringify(note));}catch{setStatus("Local storage unavailable / 無法儲存；請匯出記錄");}},[note,ready]);
 const fields:[keyof typeof empty,string,string][]=[["question","查證問題","Question"],["source","來源網址（可分行記錄）","Source URLs (one per line)"],["accessed","查閱日期與時間","Access date and time"],["observation","原文或觀察到的事實","Quoted passage or observation"],["limits","限制、衝突與未知","Limits, conflicts and unknowns"],["conclusion","目前結論及其證據","Current conclusion and supporting evidence"],["next","下一步","Next step"]];
 const content="# OSINT research note\n\n"+fields.map(([id,z,e])=>`## ${zh?z:e}\n${note[id]||"—"}`).join("\n\n");
 function download(){const url=URL.createObjectURL(new Blob([content],{type:"text/markdown;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="osint-research-note.md";a.click();URL.revokeObjectURL(url);setStatus(zh?"已匯出 Markdown 記錄":"Markdown note exported");}
 return <section className="resource-example mt-8" id="research-note"><h2 className="text-2xl">{zh?"留下一份可以復查的記錄":"Keep a note others can check"}</h2><p className="resource-muted mt-3">{zh?"草稿自動保存在這個瀏覽器，可匯出 Markdown。網址、證據、推測與未知分開記錄；本機草稿不會同步到其他裝置。":"Drafts save in this browser and can be exported as Markdown. Separate evidence, hypotheses and unknowns; local drafts do not sync across devices."}</p>{suggestedQuestion && <button className="resource-secondary mt-4" onClick={()=>{setNote(n=>({...n,question:suggestedQuestion}));setStatus(zh?"已更新問題；原有筆記保留，請確認證據是否仍適用。":"Question updated; existing notes remain. Check whether their evidence still applies.");}}>{zh?"把這個任務設為查證問題":"Use this task as the question"}</button>}<details className="mt-4"><summary>{zh?"打開查證記錄":"Open research note"}</summary><div className="resource-form-grid mt-4">{fields.map(([id,z,e])=><div key={id}><label htmlFor={`note-${id}`}>{zh?z:e}</label><textarea id={`note-${id}`} rows={id==="conclusion"||id==="observation"?4:2} value={note[id]} disabled={!ready} onChange={event=>setNote(n=>({...n,[id]:event.target.value}))}/></div>)}</div><div className="resource-chips mt-4"><button className="resource-primary" onClick={download}>{zh?"匯出記錄":"Export note"}</button><button className="resource-secondary" onClick={async()=>{try{await navigator.clipboard.writeText(content);setStatus(zh?"已複製記錄":"Note copied");}catch{setStatus(zh?"複製失敗，請使用匯出":"Copy failed; use export");}}}>{zh?"複製記錄":"Copy note"}</button></div></details><p role="status" className="resource-small mt-3">{status}</p></section>;
}
