"use client";
import { useState } from "react";
import Link from "next/link";
import { useLocale } from "@/lib/locale-context";
const cases=[
 {id:"company",workflow:"company-organization-research",zh:"公司登記",en:"Company records",questionZh:"示例公司有登記記錄，是否就能判斷它值得信任？",questionEn:"An example company has a registration record. Does that establish trustworthiness?",answerZh:"登記能確認法律主體；經營品質與可信度需要其他證據。下一步核對編號、日期、官網和申報內容。",answerEn:"Registration identifies a legal entity. Business quality and trust require other evidence. Compare identifiers, dates, websites and filings."},
 {id:"person",workflow:"public-records-research",zh:"同名人物",en:"Matching names",questionZh:"兩個公開檔案姓名相同、單位不同，能否直接合併為同一人？",questionEn:"Two public profiles share a name but list different employers. Can you merge them as one person?",answerZh:"不能。單位不同可能是職涯變動，也可能是同名。比較時間、原始機構頁面與其他一致線索，證據不足時保留未知。",answerEn:"No. Different employers could reflect a career change or a namesake. Compare dates, original institutional pages and other consistent clues; retain uncertainty."},
 {id:"image",workflow:"image-verification-geolocation",zh:"圖片背景",en:"Image context",questionZh:"搜尋找到一張較早的相同照片，是否就找到了原作者？",questionEn:"An older matching photo appears in search. Have you found the original creator?",answerZh:"未必。較早被索引不等於最初發布。閱讀來源頁、核對拍攝與發布時間，再比較其他副本及圖片中的地標。",answerEn:"Not necessarily. Earlier indexing is not first publication. Inspect the source page, capture and publication dates, other copies and visible landmarks."},
 {id:"website",workflow:"domain-reconnaissance",zh:"網站與轉載",en:"Websites and copies",questionZh:"三個網站都引用同一份公告，是否算三個獨立證據？",questionEn:"Three websites cite the same announcement. Is that three independent pieces of evidence?",answerZh:"不是。追溯原公告，再找獨立資料佐證。歷史存檔反映保存版本，也不能直接代表網站目前的內容。",answerEn:"No. Trace the original announcement and find independent corroboration. Archived versions also do not necessarily represent current content."}
];
export default function LearnPractice(){const {locale}=useLocale();const zh=locale==="zh-TW";const [answers,setAnswers]=useState<Record<string,boolean>>({});return <section className="mt-10" id="practice"><h2 className="text-2xl">{zh?"用四個小任務練習判斷":"Practise with four small tasks"}</h2><p className="resource-muted mt-3">{zh?"這些是教學情境。選擇答案、閱讀理由，再用相同方法查詢。":"These are teaching scenarios. Choose an answer, read the reasoning, then try the method."}</p><div className="resource-lesson-grid mt-5">{cases.map(c=><article key={c.id}><p className="resource-eyebrow">{zh?c.zh:c.en}</p><h3 className="text-lg mt-2">{zh?c.questionZh:c.questionEn}</h3><div className="resource-chips mt-4">{[true,false].map(choice=><button key={String(choice)} className="resource-chip" aria-pressed={answers[c.id]===choice} onClick={()=>setAnswers(a=>({...a,[c.id]:choice}))}>{choice?(zh?"可以":"Yes"):(zh?"證據還不夠":"Not enough evidence")}</button>)}</div>{c.id in answers&&<div role="status" className="resource-feedback mt-4"><strong>{answers[c.id]?(zh?"先看看缺少的證據":"Consider the missing evidence"):(zh?"判斷正確":"Correct")}</strong><p>{zh?c.answerZh:c.answerEn}</p><div className="resource-chips mt-3"><Link className="resource-text-link" href={`/search?intent=${c.id}&q=${encodeURIComponent(zh?c.zh:c.id)}&goal=all`}>{zh?"找這類資源":"Find resources"}</Link><Link className="resource-text-link" href={`/workflows/${c.workflow}`}>{zh?"完整操作流程":"Full workflow"}</Link></div></div>}</article>)}</div></section>;}
