#!/usr/bin/env python3
"""Phase 6B — add Crypto, Radio/RF, IoT tools to tools.json."""
import json
from pathlib import Path

TOOLS_FILE = Path(__file__).resolve().parent.parent / "apps" / "web" / "data" / "tools.json"
REV = {"status": "manually_reviewed", "reviewed_by": "admin",
       "reviewed_at": "2026-05-08T00:00:00Z", "notes": None}

NEW_TOOLS = [

    # ─── Crypto & Blockchain ────────────────────────────────────────────────
    {
        "id": "blockchain-explorer",
        "name": "Blockchain.com Explorer",
        "url": "https://www.blockchain.com/explorer",
        "raw_description": "Bitcoin and Ethereum blockchain explorer by Blockchain.com.",
        "description_en": "Blockchain.com's public explorer provides free lookup of Bitcoin and Ethereum addresses, transactions, and block data with no account required. Displays address balance, transaction history, and linked addresses. A reliable first-pass tool for confirming wallet activity before moving to more specialized analytics.",
        "description_zh_tw": "Blockchain.com 的公開瀏覽器免費提供比特幣和以太坊地址、交易及區塊數據查詢，無需帳號。顯示地址餘額、交易歷史及關聯地址，是進行更深入分析前的可靠初步核查工具。",
        "use_cases": [
            "Look up a Bitcoin address to retrieve its full transaction history and current balance",
            "Verify whether a specific transaction hash has been confirmed on the network",
            "Enumerate all addresses that have transacted with a wallet under investigation"
        ],
        "tags": ["cryptocurrency", "bitcoin", "ethereum", "blockchain", "explorer"],
        "pricing": "free",
        "difficulty": "beginner",
        "target_types": ["cryptocurrency"],
        "platforms": ["web"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Crypto & Blockchain",
        "source_permalink": "https://www.blockchain.com/explorer",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Most recognized free BTC/ETH explorer; standard starting point for crypto OSINT.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "etherscan",
        "name": "Etherscan",
        "url": "https://etherscan.io/",
        "raw_description": "Ethereum blockchain explorer and analytics platform.",
        "description_en": "The primary public block explorer for the Ethereum network. Allows lookup of ETH addresses, ERC-20/ERC-721 token transfers, smart contract interactions, and gas usage. The 'Internal Txns' tab reveals contract-to-contract transfers that standard wallet displays hide. Free with optional API tier.",
        "description_zh_tw": "以太坊網絡的主要公開區塊瀏覽器，支援 ETH 地址、ERC-20/ERC-721 代幣轉移、智能合約互動及 Gas 使用量查詢。「Internal Txns」標籤可揭示普通錢包介面隱藏的合約間轉帳。免費提供可選 API。",
        "use_cases": [
            "Trace ERC-20 token flows through a wallet address to identify exchange deposits and withdrawals",
            "Inspect smart contract interactions to identify what protocols a wallet has used",
            "Use the API to batch-query multiple addresses for automated investigation workflows"
        ],
        "tags": ["cryptocurrency", "ethereum", "blockchain", "explorer", "smart-contracts"],
        "pricing": "freemium",
        "difficulty": "beginner",
        "target_types": ["cryptocurrency"],
        "platforms": ["web", "api"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Crypto & Blockchain",
        "source_permalink": "https://etherscan.io/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Canonical Ethereum explorer; required for any ETH/ERC-20 investigation.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "breadcrumbs",
        "name": "Breadcrumbs",
        "url": "https://www.breadcrumbs.app/",
        "raw_description": "Visual blockchain transaction investigation tool.",
        "description_en": "Free visual blockchain analytics platform that renders wallet transaction graphs interactively. Trace multi-hop fund flows across Bitcoin and Ethereum, annotate addresses with labels, and share investigation graphs. Designed for OSINT investigators rather than enterprise compliance, with an accessible no-install web interface.",
        "description_zh_tw": "免費的視覺化區塊鏈分析平台，以互動圖形呈現錢包交易關係，可追蹤比特幣和以太坊的多跳資金流向、標注地址標籤並分享調查圖表，專為 OSINT 調查人員設計，無需安裝。",
        "use_cases": [
            "Visualize fund flow from a suspicious wallet across multiple hops to identify destination exchanges",
            "Annotate and share a blockchain investigation graph with collaborators",
            "Identify cluster patterns in a wallet's transaction history to detect mixing or layering"
        ],
        "tags": ["cryptocurrency", "blockchain", "visualization", "graph", "investigation"],
        "pricing": "freemium",
        "difficulty": "beginner",
        "target_types": ["cryptocurrency", "organization"],
        "platforms": ["web"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Crypto & Blockchain",
        "source_permalink": "https://www.breadcrumbs.app/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Best free visual blockchain graph tool for non-enterprise investigators.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "arkham-intelligence",
        "name": "Arkham Intelligence",
        "url": "https://platform.arkhamintelligence.com/",
        "raw_description": "On-chain entity attribution and blockchain intelligence platform.",
        "description_en": "Arkham Intelligence maps on-chain addresses to real-world entities — exchanges, funds, protocols, and individuals — using AI-assisted attribution and a community bounty system. Free public tier allows address and entity lookups with partial graph access. Notable for attributing previously pseudonymous wallets through behavioral analysis and transaction pattern matching.",
        "description_zh_tw": "Arkham Intelligence 透過 AI 輔助歸因和社群懸賞系統，將鏈上地址映射至真實世界實體（交易所、基金、協議和個人）。免費公開層允許地址和實體查詢，以行為分析和交易模式匹配歸因先前匿名的錢包。",
        "use_cases": [
            "Look up an address to see if Arkham has attributed it to a known entity such as an exchange or fund",
            "Trace large transfers between labeled entities to map fund movement at institutional scale",
            "Use the portfolio view to assess the full holdings and activity of a known wallet cluster"
        ],
        "tags": ["cryptocurrency", "blockchain", "attribution", "intelligence", "entity-labeling"],
        "pricing": "freemium",
        "difficulty": "intermediate",
        "target_types": ["cryptocurrency", "person", "organization"],
        "platforms": ["web"],
        "ethical_flag": True,
        "ethics_note": "Arkham de-anonymizes wallet holders by linking on-chain addresses to real-world identities, including private individuals. Use only for authorized investigative or compliance purposes.",
        "source_section": "Crypto & Blockchain",
        "source_permalink": "https://platform.arkhamintelligence.com/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Leading public-tier blockchain attribution platform; unique entity-labeling dataset.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "bubblemaps",
        "name": "Bubblemaps",
        "url": "https://bubblemaps.io/",
        "raw_description": "Token holder cluster visualization for blockchain tokens.",
        "description_en": "Bubblemaps visualizes token holder distribution as interactive bubble charts, revealing wallet clusters, insider allocations, and coordinated holding patterns for DeFi tokens. Useful for identifying undisclosed concentrated ownership, team wallet clusters, and wash-trading patterns that are not obvious from raw on-chain data.",
        "description_zh_tw": "Bubblemaps 以互動氣泡圖呈現代幣持有者分佈，揭示 DeFi 代幣中的錢包叢集、內部人配額和協調持倉模式，適用於識別未披露的集中持倉、團隊錢包叢集和原始鏈上數據中不易察覺的洗盤模式。",
        "use_cases": [
            "Visualize token holder clusters for a DeFi project to detect undisclosed insider wallets",
            "Identify coordinated selling patterns across multiple wallets in a token's holder distribution",
            "Compare holder cluster changes over time to track token distribution manipulation"
        ],
        "tags": ["cryptocurrency", "blockchain", "visualization", "token-analysis", "defi"],
        "pricing": "freemium",
        "difficulty": "beginner",
        "target_types": ["cryptocurrency", "organization"],
        "platforms": ["web"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Crypto & Blockchain",
        "source_permalink": "https://bubblemaps.io/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Unique token holder visualization with no direct equivalent for DeFi cluster analysis.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "blockchair",
        "name": "Blockchair",
        "url": "https://blockchair.com/",
        "raw_description": "Multi-blockchain explorer and analytics engine.",
        "description_en": "Blockchair is a privacy-focused multi-blockchain explorer supporting Bitcoin, Ethereum, Litecoin, Cardano, Solana, and 15+ other chains in a single interface. Offers full-text transaction memo search, address clustering, UTXO analysis, and bulk CSV export. Notably does not sell user search data to analytics firms.",
        "description_zh_tw": "Blockchair 是注重隱私的多鏈瀏覽器，在單一介面支援比特幣、以太坊、萊特幣、Cardano、Solana 等 15+ 個鏈，提供全文交易備忘錄搜尋、地址叢集、UTXO 分析和批量 CSV 導出，且不向分析公司出售用戶搜尋數據。",
        "use_cases": [
            "Search transaction memos across multiple chains to find references to known identifiers",
            "Export address transaction history as CSV for offline analysis or evidence packaging",
            "Cross-chain investigation: track funds from Bitcoin through Ethereum to identify bridge usage"
        ],
        "tags": ["cryptocurrency", "blockchain", "explorer", "multi-chain", "analytics"],
        "pricing": "freemium",
        "difficulty": "beginner",
        "target_types": ["cryptocurrency"],
        "platforms": ["web", "api"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Crypto & Blockchain",
        "source_permalink": "https://blockchair.com/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Best multi-chain explorer; memo search and CSV export are unique differentiators.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "metasleuth",
        "name": "MetaSleuth",
        "url": "https://metasleuth.io/",
        "raw_description": "Blockchain investigation and fund tracking tool by BlockSec.",
        "description_en": "MetaSleuth by BlockSec is a free visual blockchain investigation platform for tracing fund flows, labeling addresses, and sharing investigation reports. Supports multi-chain analysis including Ethereum, BNB Chain, Polygon, and others. Notable for detecting bridge-crossing transactions that move funds between chains to obscure trails.",
        "description_zh_tw": "BlockSec 開發的 MetaSleuth 是免費的視覺化區塊鏈調查平台，用於追蹤資金流向、標記地址和分享調查報告，支援以太坊、BNB Chain、Polygon 等多鏈分析，尤其擅長偵測跨鏈橋交易以追蹤跨鏈資金轉移痕跡。",
        "use_cases": [
            "Trace multi-chain fund movements to follow assets transferred across bridge protocols",
            "Generate a shareable investigation report linking wallet addresses to identified entities",
            "Label custom addresses within an investigation graph and export for evidence documentation"
        ],
        "tags": ["cryptocurrency", "blockchain", "visualization", "multi-chain", "investigation"],
        "pricing": "freemium",
        "difficulty": "intermediate",
        "target_types": ["cryptocurrency", "organization"],
        "platforms": ["web"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Crypto & Blockchain",
        "source_permalink": "https://metasleuth.io/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Best free multi-chain bridge-crossing tracker; strong DeFi incident investigation tool.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "oxt",
        "name": "OXT",
        "url": "https://oxt.me/",
        "raw_description": "Bitcoin transaction graph analysis and privacy research tool.",
        "description_en": "OXT is a free Bitcoin-specific blockchain explorer focused on transaction graph analysis and clustering heuristics. Implements UTXO-based address clustering, coin tracing, and privacy analysis techniques used by researchers. Particularly useful for studying Bitcoin privacy properties and tracing coinjoins or mixer outputs.",
        "description_zh_tw": "OXT 是免費的比特幣專用區塊鏈瀏覽器，專注於交易圖分析和聚類啟發式算法，實現基於 UTXO 的地址叢集化、代幣追蹤和研究人員使用的隱私分析技術，尤其適合研究比特幣隱私特性及追蹤 CoinJoin 或混幣輸出。",
        "use_cases": [
            "Cluster Bitcoin addresses using common-input-ownership heuristics to identify wallet boundaries",
            "Analyze coinjoin transactions to assess whether effective privacy was achieved",
            "Study the UTXO graph structure of a Bitcoin address to identify change outputs"
        ],
        "tags": ["cryptocurrency", "bitcoin", "graph", "clustering", "privacy-analysis"],
        "pricing": "free",
        "difficulty": "advanced",
        "target_types": ["cryptocurrency"],
        "platforms": ["web"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Crypto & Blockchain",
        "source_permalink": "https://oxt.me/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Best free Bitcoin UTXO clustering tool; unique heuristic capabilities.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "dune-analytics",
        "name": "Dune Analytics",
        "url": "https://dune.com/",
        "raw_description": "Community-driven blockchain analytics platform with SQL queries.",
        "description_en": "Dune Analytics allows anyone to query blockchain data using SQL, with a vast library of community-published dashboards covering DeFi protocols, NFT markets, and wallet activity. Free tier enables query execution and dashboard access. Useful for investigators who need custom on-chain queries that go beyond what standard explorers provide.",
        "description_zh_tw": "Dune Analytics 允許任何人使用 SQL 查詢區塊鏈數據，擁有涵蓋 DeFi 協議、NFT 市場和錢包活動的大量社群發布儀表板。免費層支援查詢執行和儀表板訪問，適合需要超越標準瀏覽器能力的自定義鏈上查詢的調查人員。",
        "use_cases": [
            "Run custom SQL queries to identify all wallets that interacted with a specific smart contract",
            "Access community dashboards tracking known exploit addresses or hacker wallet patterns",
            "Analyze protocol-level fund flows to map money movement through DeFi applications"
        ],
        "tags": ["cryptocurrency", "blockchain", "analytics", "sql", "defi", "dashboards"],
        "pricing": "freemium",
        "difficulty": "intermediate",
        "target_types": ["cryptocurrency", "organization"],
        "platforms": ["web"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Crypto & Blockchain",
        "source_permalink": "https://dune.com/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Only free SQL blockchain query platform; irreplaceable for custom on-chain analysis.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "crystal-intelligence",
        "name": "Crystal Intelligence",
        "url": "https://crystalintelligence.com/",
        "raw_description": "Blockchain analytics and compliance intelligence platform.",
        "description_en": "Crystal Intelligence provides blockchain transaction monitoring, risk scoring, and entity attribution across Bitcoin, Ethereum, and 100+ assets. Free account offers limited lookups and risk score checks. Primarily used by compliance teams but accessible enough for investigators who need to check an address's risk profile against known hacking, darknet, and ransomware entities.",
        "description_zh_tw": "Crystal Intelligence 提供比特幣、以太坊及 100+ 種資產的區塊鏈交易監控、風險評分和實體歸因。免費帳號提供有限查詢和風險評分核查，主要用於合規團隊，也適合需要對照已知駭客、暗網和勒索軟體實體核查地址風險檔案的調查人員。",
        "use_cases": [
            "Check whether a wallet address has exposure to known darknet markets or sanctioned entities",
            "Obtain a risk score for a Bitcoin address before accepting a payment",
            "Identify the source of funds for a wallet through automated risk categorization"
        ],
        "tags": ["cryptocurrency", "blockchain", "risk-scoring", "compliance", "attribution"],
        "pricing": "freemium",
        "difficulty": "beginner",
        "target_types": ["cryptocurrency", "organization"],
        "platforms": ["web", "api"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Crypto & Blockchain",
        "source_permalink": "https://crystalintelligence.com/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Accessible freemium risk-scoring alternative to Chainalysis for non-enterprise use.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "chainalysis-reactor",
        "name": "Chainalysis Reactor",
        "url": "https://www.chainalysis.com/chainalysis-reactor/",
        "raw_description": "Enterprise blockchain investigation and transaction tracing platform.",
        "description_en": "Chainalysis Reactor is the industry-standard enterprise blockchain investigation platform, used by law enforcement agencies, regulators, and financial institutions across 70+ countries. Traces fund flows, de-anonymizes wallets through proprietary clustering, and links on-chain activity to off-chain identities from exchange KYC data. Paid enterprise licensing required; included here as a reference standard.",
        "description_zh_tw": "Chainalysis Reactor 是被 70+ 國執法機構、監管機構和金融機構使用的行業標準企業級區塊鏈調查平台，追蹤資金流動、通過專有叢集化去匿名化錢包，並將鏈上活動與交易所 KYC 數據中的真實身份關聯。需企業授權，此處收錄作為行業參考標準。",
        "use_cases": [
            "Conduct court-admissible blockchain tracing with full audit trail for law enforcement use",
            "Access proprietary exchange attribution data to identify where illicit funds were cashed out",
            "Generate regulatory compliance reports linking transaction clusters to real-world entities"
        ],
        "tags": ["cryptocurrency", "blockchain", "attribution", "enterprise", "law-enforcement"],
        "pricing": "paid",
        "difficulty": "advanced",
        "target_types": ["cryptocurrency", "person", "organization"],
        "platforms": ["web"],
        "ethical_flag": True,
        "ethics_note": "Uses proprietary KYC data from exchange partners to de-anonymize wallet holders; access implies legal authority or enterprise compliance use case.",
        "source_section": "Crypto & Blockchain",
        "source_permalink": "https://www.chainalysis.com/chainalysis-reactor/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Industry-standard law enforcement blockchain tool; important reference even at enterprise tier.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "hyperbot-network",
        "name": "Hyperbot",
        "url": "https://hyperbot.network/",
        "raw_description": "AI-powered on-chain intelligence for Hyperliquid perpetual DEX.",
        "description_en": "Hyperbot is an AI-powered on-chain intelligence platform focused on Hyperliquid and Aster perpetual DEXs. It provides whale tracking, smart money identification, and PnL curve analysis across 600,000+ Hyperliquid addresses using natural language queries and AI tagging. Useful for investigators tracing large-position holders, attributing wallet clusters, and monitoring coordinated trading behavior on decentralized perpetual exchanges.",
        "description_zh_tw": "Hyperbot 是以 AI 驅動的鏈上情報平台，專注於 Hyperliquid 與 Aster 永續 DEX，透過自然語言查詢與 AI 標籤追蹤逾 60 萬個 Hyperliquid 地址的巨鯨動向、聰明錢識別與損益曲線分析，適用於追蹤大倉位持有者、歸因錢包叢集及監控協調交易行為。",
        "use_cases": [
            "Identify top PnL wallets on Hyperliquid to attribute coordinated market activity to known entities",
            "Monitor whale address movements and alert patterns for on-chain behavioral profiling",
            "Cross-reference large trader addresses across DEX leaderboards to build a trader identity graph"
        ],
        "tags": ["cryptocurrency", "blockchain", "defi", "whale-tracking", "behavioral-analysis"],
        "pricing": "freemium",
        "difficulty": "intermediate",
        "target_types": ["cryptocurrency", "person", "organization"],
        "platforms": ["web", "api"],
        "ethical_flag": True,
        "ethics_note": "Wallet attribution and behavioral profiling of traders may expose pseudonymous individuals; use only for legitimate investigative or compliance purposes.",
        "source_section": "Crypto & Blockchain",
        "source_permalink": "https://hyperbot.network/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Unique AI-powered DEX trader profiling tool with no mainstream equivalent.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },

    # ─── Radio & RF Intelligence ────────────────────────────────────────────
    {
        "id": "flightradar24",
        "name": "Flightradar24",
        "url": "https://www.flightradar24.com/",
        "raw_description": "Real-time ADS-B aircraft tracking platform.",
        "description_en": "Flightradar24 aggregates ADS-B, MLAT, and FAA data to display real-time and historical positions for 180,000+ flights per day worldwide. Free tier shows current positions and basic flight data. Investigators use it to verify aircraft movements, track tail numbers, identify routes for a specific aircraft, and cross-reference with ground events.",
        "description_zh_tw": "Flightradar24 聚合 ADS-B、MLAT 和 FAA 數據，每日即時顯示全球逾 18 萬架次航班的位置。免費層提供當前位置和基本航班數據，調查人員可用它核實飛機動向、追蹤尾號、識別特定飛機的航線並與地面事件交叉比對。",
        "use_cases": [
            "Track the real-time position and route of an aircraft by registration or flight number",
            "Review historical flight paths for a specific tail number to establish movement patterns",
            "Verify whether a private aircraft was present at a specific location during an event"
        ],
        "tags": ["adsb", "aircraft", "aviation", "tracking", "geolocation", "sigint"],
        "pricing": "freemium",
        "difficulty": "beginner",
        "target_types": ["network", "geolocation", "organization"],
        "platforms": ["web", "mobile"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Radio & RF Intelligence",
        "source_permalink": "https://www.flightradar24.com/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Widest global ADS-B coverage; standard tool for aircraft OSINT.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "adsbexchange",
        "name": "ADS-B Exchange",
        "url": "https://www.adsbexchange.com/",
        "raw_description": "Unfiltered community ADS-B flight tracking without government request compliance.",
        "description_en": "ADS-B Exchange is a community-run ADS-B aggregator that does not comply with government or corporate requests to remove or block aircraft from its feed — unlike Flightradar24. This makes it the preferred source for tracking military, law enforcement, and government aircraft that commercial platforms occasionally suppress. Free data access via web and API.",
        "description_zh_tw": "ADS-B Exchange 是社群運營的 ADS-B 聚合器，不遵從政府或企業的移除/屏蔽飛機請求，有別於 Flightradar24，是追蹤偶爾被商業平台壓制的軍用、執法和政府飛機的首選來源，免費提供網頁和 API 數據訪問。",
        "use_cases": [
            "Track military or government aircraft that are hidden or suppressed on commercial ADS-B platforms",
            "Access unfiltered flight data via API for automated aircraft monitoring workflows",
            "Verify historical aircraft positions when a commercial platform has removed the track"
        ],
        "tags": ["adsb", "aircraft", "aviation", "sigint", "unfiltered", "military"],
        "pricing": "free",
        "difficulty": "beginner",
        "target_types": ["network", "geolocation", "organization"],
        "platforms": ["web", "api"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Radio & RF Intelligence",
        "source_permalink": "https://www.adsbexchange.com/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Only unfiltered ADS-B source; critical for government/military aircraft OSINT.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "marinetraffic",
        "name": "MarineTraffic",
        "url": "https://www.marinetraffic.com/",
        "raw_description": "AIS vessel tracking and maritime intelligence platform.",
        "description_en": "MarineTraffic is the leading public AIS vessel tracking platform, displaying real-time and historical positions for ships worldwide using Automatic Identification System (AIS) radio broadcasts. Free tier provides current vessel positions and basic voyage data. Used by investigators to track ship movements, verify port calls, and identify flag-of-convenience vessels.",
        "description_zh_tw": "MarineTraffic 是領先的公開 AIS 船舶追蹤平台，利用自動識別系統（AIS）無線電廣播顯示全球船舶的即時和歷史位置。免費層提供當前船舶位置和基本航次數據，用於追蹤船舶動向、核實靠港情況和識別方便旗船舶。",
        "use_cases": [
            "Track a vessel's current position and review its historical voyage route and port calls",
            "Identify all vessels registered under a specific flag state or operating company",
            "Verify whether a ship was in a specific location during a reported maritime incident"
        ],
        "tags": ["ais", "maritime", "vessel", "tracking", "geolocation", "rf", "sigint"],
        "pricing": "freemium",
        "difficulty": "beginner",
        "target_types": ["network", "geolocation", "organization"],
        "platforms": ["web", "api"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Radio & RF Intelligence",
        "source_permalink": "https://www.marinetraffic.com/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Primary public AIS vessel tracker; essential for maritime investigation.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "opensky-network",
        "name": "OpenSky Network",
        "url": "https://opensky-network.org/",
        "raw_description": "Open academic ADS-B network providing historical flight data.",
        "description_en": "OpenSky Network is a non-profit ADS-B aggregation network operated by academic institutions, offering free historical flight data download for research purposes. Unlike commercial platforms, it provides access to raw ADS-B records for specific time windows and geographic regions. Valuable when you need historical aircraft data that commercial platforms restrict behind paywalls.",
        "description_zh_tw": "OpenSky Network 是由學術機構運營的非營利 ADS-B 聚合網絡，免費提供用於研究目的的歷史飛行數據下載，提供特定時間窗口和地理區域的原始 ADS-B 記錄，在商業平台將歷史數據鎖在付費牆後尤為有價值。",
        "use_cases": [
            "Download historical ADS-B records for a geographic region during a specific time window",
            "Access raw flight data for investigative analysis without commercial platform restrictions",
            "Cross-reference aircraft tracks from different data sources to verify position accuracy"
        ],
        "tags": ["adsb", "aircraft", "aviation", "sigint", "open-data", "historical"],
        "pricing": "free",
        "difficulty": "intermediate",
        "target_types": ["network", "geolocation"],
        "platforms": ["web", "api"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Radio & RF Intelligence",
        "source_permalink": "https://opensky-network.org/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Only free source of raw historical ADS-B data for research use.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "websdr",
        "name": "WebSDR",
        "url": "http://www.websdr.org/",
        "raw_description": "Network of web-accessible software-defined radio receivers.",
        "description_en": "WebSDR hosts a network of publicly accessible Software Defined Radio (SDR) receivers connected to the internet, allowing anyone to tune and listen to radio frequencies worldwide through a web browser without any hardware. Useful for monitoring public shortwave broadcasts, amateur radio activity, and HF signals from specific geographic regions.",
        "description_zh_tw": "WebSDR 托管一個可通過網絡訪問的軟件定義無線電（SDR）接收器網絡，允許任何人在不需要任何硬件的情況下通過網絡瀏覽器調諧和收聽全球無線電頻率，適用於監聽特定地理區域的公共短波廣播、業餘無線電活動和 HF 信號。",
        "use_cases": [
            "Listen to public shortwave broadcasts or amateur radio from a specific geographic region",
            "Monitor HF frequencies used for known public emergency or maritime communications",
            "Verify whether a specific frequency is being used in a target area without local hardware"
        ],
        "tags": ["sdr", "rf", "radio", "spectrum", "shortwave", "monitoring"],
        "pricing": "free",
        "difficulty": "beginner",
        "target_types": ["network", "geolocation"],
        "platforms": ["web"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Radio & RF Intelligence",
        "source_permalink": "http://www.websdr.org/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Unique zero-hardware SDR access; only public listening network of its kind.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "sigidwiki",
        "name": "Signal Identification Wiki",
        "url": "https://www.sigidwiki.com/",
        "raw_description": "Community wiki for identifying unknown radio signals.",
        "description_en": "Signal Identification Wiki is a community-maintained reference database of radio signal types with audio samples, waterfall images, and technical parameters. Used by investigators and radio operators to identify an unknown signal's origin, modulation, and likely purpose. Covers military, commercial, maritime, and amateur signal types.",
        "description_zh_tw": "Signal Identification Wiki 是社群維護的無線電信號類型參考資料庫，包含音頻樣本、瀑布圖和技術參數，供調查人員和無線電操作員識別未知信號的來源、調制方式和可能用途，涵蓋軍用、商用、海事和業餘信號類型。",
        "use_cases": [
            "Identify an unknown radio signal by comparing its waterfall pattern to the signal database",
            "Determine the modulation type and likely use case of a signal recorded during monitoring",
            "Research which agencies or services typically use a specific frequency band and signal type"
        ],
        "tags": ["rf", "sigint", "signal-identification", "spectrum", "radio"],
        "pricing": "free",
        "difficulty": "intermediate",
        "target_types": ["network"],
        "platforms": ["web"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Radio & RF Intelligence",
        "source_permalink": "https://www.sigidwiki.com/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Definitive reference for radio signal identification; no comparable free alternative.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "radioreference",
        "name": "RadioReference",
        "url": "https://www.radioreference.com/",
        "raw_description": "Comprehensive radio frequency and trunked system database.",
        "description_en": "RadioReference is the world's largest radio frequency database, covering police, fire, EMS, federal, and military trunked radio systems across the US and internationally. Free tier provides frequency lookups by location, agency, or system. Used by investigators to identify what public-safety agencies are operating in a specific area and what frequencies they use.",
        "description_zh_tw": "RadioReference 是全球最大的無線電頻率資料庫，涵蓋美國及國際的警察、消防、急救、聯邦和軍用集群無線電系統。免費層提供按地點、機構或系統的頻率查詢，供調查人員識別特定區域的公共安全機構及其使用頻率。",
        "use_cases": [
            "Look up all public-safety radio frequencies operating in a specific city or county",
            "Identify the trunked radio system used by a law enforcement agency for monitoring authorization",
            "Research federal agency radio systems operating in a target geographic area"
        ],
        "tags": ["rf", "radio", "frequency-database", "public-safety", "sigint"],
        "pricing": "freemium",
        "difficulty": "beginner",
        "target_types": ["network", "organization"],
        "platforms": ["web"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Radio & RF Intelligence",
        "source_permalink": "https://www.radioreference.com/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "World's most comprehensive public radio frequency database; no direct equivalent.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "liveatc",
        "name": "LiveATC",
        "url": "https://www.liveatc.net/",
        "raw_description": "Live and archived air traffic control audio feeds worldwide.",
        "description_en": "LiveATC streams live and archived Air Traffic Control (ATC) radio communications from airports worldwide, contributed by volunteer feeders. Coverage spans 2,000+ airports across 150+ countries. Investigators and journalists use it to verify reported aircraft incidents, listen to communications during known events, and access archived feeds for specific dates.",
        "description_zh_tw": "LiveATC 從全球 150+ 國家、2,000+ 機場直播和存檔空中交通管制（ATC）無線電通訊，由志願者供稿。調查人員和記者使用它核實報告的飛機事故、監聽已知事件中的通訊，並訪問特定日期的存檔供料。",
        "use_cases": [
            "Listen to ATC communications at a specific airport during a reported aviation incident",
            "Access archived ATC audio to verify what was communicated during a specific event",
            "Monitor active airport frequencies to track unusual aircraft activity in real time"
        ],
        "tags": ["rf", "aviation", "atc", "radio", "monitoring", "sigint"],
        "pricing": "freemium",
        "difficulty": "beginner",
        "target_types": ["network", "geolocation"],
        "platforms": ["web"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Radio & RF Intelligence",
        "source_permalink": "https://www.liveatc.net/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Unique archive of ATC communications; essential for aviation incident research.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "vesselfinder",
        "name": "VesselFinder",
        "url": "https://www.vesselfinder.com/",
        "raw_description": "AIS vessel tracking platform with historical voyage data.",
        "description_en": "VesselFinder is an AIS maritime tracking platform providing real-time ship positions, vessel particulars, and voyage history. Useful as a cross-reference source alongside MarineTraffic, as different platforms receive AIS from different ground station networks and may show vessels the other misses. Free tier covers current positions and basic vessel data.",
        "description_zh_tw": "VesselFinder 是提供即時船舶位置、船舶詳情和航次歷史的 AIS 海事追蹤平台，可與 MarineTraffic 交叉比對，因不同平台從不同地面站網絡接收 AIS，可能顯示對方遺漏的船舶。免費層涵蓋當前位置和基本船舶數據。",
        "use_cases": [
            "Cross-reference a vessel's position with MarineTraffic to verify AIS reporting consistency",
            "Look up vessel registration details, IMO number, and flag state for a ship under investigation",
            "Track port arrivals and departures to build a vessel's recent activity timeline"
        ],
        "tags": ["ais", "maritime", "vessel", "tracking", "rf", "geolocation"],
        "pricing": "freemium",
        "difficulty": "beginner",
        "target_types": ["network", "geolocation", "organization"],
        "platforms": ["web"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Radio & RF Intelligence",
        "source_permalink": "https://www.vesselfinder.com/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Complementary AIS coverage to MarineTraffic; different ground station network.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "airframes-io",
        "name": "Airframes",
        "url": "https://airframes.io/",
        "raw_description": "ACARS and VDL aircraft data link message decoder and archive.",
        "description_en": "Airframes decodes and archives ACARS (Aircraft Communications Addressing and Reporting System) and VDL Mode 2 data link messages broadcast by commercial aircraft. These messages contain flight plan updates, weather reports, maintenance notifications, and position reports. Provides operational intelligence beyond ADS-B, including engine performance data and pre-departure clearances.",
        "description_zh_tw": "Airframes 解碼並存檔商業飛機廣播的 ACARS 和 VDL Mode 2 數據鏈信息，包含飛行計劃更新、天氣報告、維護通知和位置報告，提供超越 ADS-B 的運營情報，包括發動機性能數據和起飛前許可。",
        "use_cases": [
            "Access ACARS message history for a specific tail number to review operational communications",
            "Decode pre-departure clearance messages to see filed flight plans before departure",
            "Monitor maintenance and fault messages for aircraft to identify operational anomalies"
        ],
        "tags": ["adsb", "acars", "aircraft", "sigint", "aviation", "rf"],
        "pricing": "free",
        "difficulty": "advanced",
        "target_types": ["network", "geolocation", "organization"],
        "platforms": ["web"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "Radio & RF Intelligence",
        "source_permalink": "https://airframes.io/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Unique ACARS archive; only public source of decoded aircraft data link messages.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },

    # ─── IoT & Smart Devices ────────────────────────────────────────────────
    {
        "id": "zoomeye",
        "name": "ZoomEye",
        "url": "https://www.zoomeye.org/",
        "raw_description": "Chinese cyberspace search engine for internet-connected devices.",
        "description_en": "ZoomEye by Knownsec is a Chinese-developed cyberspace search engine that indexes internet-facing devices and services, including industrial control systems, webcams, and network appliances. Particularly effective for discovering devices in Asia-Pacific regions that Shodan and Censys may undercount. Free tier allows limited queries. Supports Dork-style search syntax.",
        "description_zh_tw": "知道創宇開發的 ZoomEye 是中國自主研發的網絡空間搜尋引擎，索引網絡連接設備和服務，包括工業控制系統、攝影機和網絡設備，尤其擅長發現 Shodan 和 Censys 可能低估的亞太地區設備。免費層允許有限查詢，支援 Dork 式搜尋語法。",
        "use_cases": [
            "Search for exposed devices in a specific Asia-Pacific IP range not well-covered by Shodan",
            "Use ZoomEye Dork syntax to find a specific device type or firmware version globally",
            "Cross-reference a device fingerprint with ZoomEye to verify geographic distribution"
        ],
        "tags": ["iot-osint", "device-search", "cyberspace-mapping", "network-scanning"],
        "pricing": "freemium",
        "difficulty": "intermediate",
        "target_types": ["ip", "network", "domain"],
        "platforms": ["web", "api"],
        "ethical_flag": True,
        "ethics_note": "Use for passive enumeration and exposure assessment only. Do not use results to access, exploit, or interact with discovered devices without explicit authorization.",
        "source_section": "IoT & Smart Devices",
        "source_permalink": "https://www.zoomeye.org/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Best Shodan alternative for Asia-Pacific IoT coverage; distinct dataset.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "fofa",
        "name": "FOFA",
        "url": "https://en.fofa.info/",
        "raw_description": "Chinese cyberspace asset mapping and threat intelligence platform.",
        "description_en": "FOFA is a cyberspace mapping and intelligence platform developed by Baimaohui Security Research Center. It indexes internet-facing services with detailed fingerprinting, supporting searches by domain, IP, certificate, banner, and product keyword. Often surfaces devices and services in China and Southeast Asia not found in Western-operated scanners.",
        "description_zh_tw": "FOFA 是白帽匯安全研究中心開發的網絡空間測繪和情報平台，對網絡連接服務進行詳細指紋識別，支援按域名、IP、憑證、橫幅和產品關鍵字搜尋，常發現西方掃描器未收錄的中國和東南亞設備和服務。",
        "use_cases": [
            "Search for exposed services in China or Southeast Asia using certificate or banner fingerprints",
            "Identify the geographic spread of a specific IoT device model across different countries",
            "Find internet-exposed instances of specific industrial software or control panel versions"
        ],
        "tags": ["iot-osint", "cyberspace-mapping", "device-search", "fingerprinting"],
        "pricing": "freemium",
        "difficulty": "intermediate",
        "target_types": ["ip", "network", "domain"],
        "platforms": ["web", "api"],
        "ethical_flag": True,
        "ethics_note": "Passive enumeration only. Do not attempt to access or exploit any discovered services without explicit written authorization.",
        "source_section": "IoT & Smart Devices",
        "source_permalink": "https://en.fofa.info/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Superior coverage for Asian networks; complements Shodan for global IoT mapping.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "binaryedge",
        "name": "BinaryEdge",
        "url": "https://www.binaryedge.io/",
        "raw_description": "Internet-wide scan platform for attack surface and IoT exposure monitoring.",
        "description_en": "BinaryEdge continuously scans the internet to map attack surfaces, identify exposed IoT devices, and detect misconfigured services. Provides structured data on open ports, protocols, certificates, and service banners. Free tier offers limited queries. Its Tormentor scoring system highlights the most critical exposures for triage prioritization.",
        "description_zh_tw": "BinaryEdge 持續掃描互聯網以繪製攻擊面、識別暴露的 IoT 設備和偵測錯誤配置的服務，提供關於開放端口、協議、憑證和服務橫幅的結構化數據。免費層提供有限查詢，其 Tormentor 評分系統突出顯示最關鍵的暴露以供分類優先處理。",
        "use_cases": [
            "Identify all internet-exposed services for a target organization's IP range",
            "Detect misconfigured databases, storage buckets, or management interfaces in an IP block",
            "Monitor attack surface changes over time for a specific domain or organization"
        ],
        "tags": ["iot-osint", "attack-surface", "smart-devices", "network-scanning", "exposure"],
        "pricing": "freemium",
        "difficulty": "intermediate",
        "target_types": ["ip", "network", "domain", "organization"],
        "platforms": ["web", "api"],
        "ethical_flag": True,
        "ethics_note": "Attack surface data should be used defensively to assess your own infrastructure, or in authorized security assessments. Do not use to target or interact with third-party systems.",
        "source_section": "IoT & Smart Devices",
        "source_permalink": "https://www.binaryedge.io/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Structured IoT exposure data with risk scoring; distinct from Shodan in methodology.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "onyphe",
        "name": "Onyphe",
        "url": "https://www.onyphe.io/",
        "raw_description": "French cyber defense search engine for internet-facing infrastructure.",
        "description_en": "Onyphe is a European cyber threat intelligence search engine that collects data from internet scans, honeypots, dark web crawls, and threat feeds. Unlike Shodan, it combines passive DNS, WHOIS, and threat intelligence data in a single query interface. Free tier available. Used for holistic assessment of an IP or domain across multiple data sources simultaneously.",
        "description_zh_tw": "Onyphe 是歐洲網絡威脅情報搜尋引擎，從互聯網掃描、蜜罐、暗網爬取和威脅供料收集數據，與 Shodan 不同，它在單一查詢介面中結合被動 DNS、WHOIS 和威脅情報數據。提供免費層，用於跨多個數據源同時全面評估 IP 或域名。",
        "use_cases": [
            "Query an IP address to see its combined scan data, threat intelligence, and passive DNS records",
            "Find internet-exposed services that have appeared in honeypot logs or threat feeds",
            "Assess an organization's attack surface with a multi-source view not available in single-source scanners"
        ],
        "tags": ["iot-osint", "cyber-defense", "device-search", "threat-intelligence", "passive-dns"],
        "pricing": "freemium",
        "difficulty": "intermediate",
        "target_types": ["ip", "network", "domain"],
        "platforms": ["web", "api"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "IoT & Smart Devices",
        "source_permalink": "https://www.onyphe.io/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "European multi-source intelligence aggregator; unique dark web + scan data combination.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "leakix",
        "name": "LeakIX",
        "url": "https://leakix.net/",
        "raw_description": "Internet scanner focused on exposed and misconfigured services.",
        "description_en": "LeakIX specializes in identifying publicly exposed services that are misconfigured or leaking data — including open MongoDB databases, exposed Elasticsearch clusters, unprotected S3-compatible storage, and insecure IoT management interfaces. Data is collected passively and displayed with severity classifications. Free for researchers and security professionals.",
        "description_zh_tw": "LeakIX 專注於識別配置錯誤或洩露數據的公開暴露服務，包括開放的 MongoDB 資料庫、暴露的 Elasticsearch 集群、未受保護的 S3 兼容存儲和不安全的 IoT 管理介面，被動收集數據並按嚴重性分類顯示，供研究人員和安全專業人員免費使用。",
        "use_cases": [
            "Search for exposed databases or storage buckets associated with a target domain or IP range",
            "Identify publicly visible IoT management consoles or admin panels in a target organization's infrastructure",
            "Check whether a specific technology stack has known misconfiguration patterns visible at an IP"
        ],
        "tags": ["iot-osint", "exposed-services", "misconfiguration", "data-exposure", "smart-devices"],
        "pricing": "free",
        "difficulty": "intermediate",
        "target_types": ["ip", "network", "domain"],
        "platforms": ["web", "api"],
        "ethical_flag": True,
        "ethics_note": "Data reflects real misconfigured production systems. Use only for assessing your own infrastructure or reporting to asset owners. Do not access or extract data from discovered exposed services.",
        "source_section": "IoT & Smart Devices",
        "source_permalink": "https://leakix.net/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Unique focus on misconfiguration-based exposure; data not available from generic scanners.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "criminalip",
        "name": "Criminal IP",
        "url": "https://www.criminalip.io/",
        "raw_description": "Attack surface intelligence engine with AI-powered threat scoring.",
        "description_en": "Criminal IP is a cyber threat intelligence search engine that continuously scans the internet and assigns AI-driven risk scores to IP addresses, domains, and exposed services. Features domain and certificate search, port scan history, and a vulnerability mapping layer. Free tier available. Particularly strong for identifying high-risk IoT and OT device exposures.",
        "description_zh_tw": "Criminal IP 是持續掃描互聯網並對 IP 地址、域名和暴露服務賦予 AI 驅動風險評分的網絡威脅情報搜尋引擎，具有域名和憑證搜尋、端口掃描歷史和漏洞映射層，免費層可用，尤其擅長識別高風險 IoT 和 OT 設備暴露。",
        "use_cases": [
            "Obtain an AI risk score for an IP address to quickly triage its threat level",
            "Search for exposed IoT device types by banner or certificate fingerprint with risk scoring",
            "Review port scan history for an IP to identify recently opened or closed services"
        ],
        "tags": ["iot-osint", "attack-surface", "device-intelligence", "smart-devices", "risk-scoring"],
        "pricing": "freemium",
        "difficulty": "beginner",
        "target_types": ["ip", "network", "domain"],
        "platforms": ["web", "api"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "IoT & Smart Devices",
        "source_permalink": "https://www.criminalip.io/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Emerging alternative to Shodan with AI risk scoring; strong IoT threat detection.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "fullhunt",
        "name": "FullHunt",
        "url": "https://fullhunt.io/",
        "raw_description": "Attack surface discovery and monitoring platform.",
        "description_en": "FullHunt maps an organization's entire internet-exposed attack surface — domains, subdomains, IP ranges, and associated open ports and services — from a single domain or company name query. Free tier covers basic asset discovery. Useful for building a complete picture of an organization's IoT and web-facing infrastructure exposure before investigation.",
        "description_zh_tw": "FullHunt 從單個域名或公司名稱查詢映射組織的整個互聯網暴露攻擊面，包括域名、子域名、IP 範圍及關聯的開放端口和服務。免費層涵蓋基本資產發現，適用於在調查前建立組織 IoT 和面向網絡的基礎設施暴露的完整圖景。",
        "use_cases": [
            "Enumerate all internet-exposed assets for a target organization from a single domain query",
            "Identify subdomains and associated infrastructure that a company may not be aware of",
            "Monitor attack surface changes for an organization over time to detect new exposures"
        ],
        "tags": ["iot-osint", "attack-surface", "asset-discovery", "subdomain-enumeration"],
        "pricing": "freemium",
        "difficulty": "beginner",
        "target_types": ["domain", "ip", "network", "organization"],
        "platforms": ["web", "api"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "IoT & Smart Devices",
        "source_permalink": "https://fullhunt.io/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Simplest full attack surface view for an organization; no equivalent free tool.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
    {
        "id": "publicwww",
        "name": "PublicWWW",
        "url": "https://publicwww.com/",
        "raw_description": "Source code and digital fingerprint search engine for websites.",
        "description_en": "PublicWWW indexes the source code of billions of websites, allowing search by HTML snippet, JavaScript library, meta tag, tracking ID, or technology fingerprint. Useful for finding IoT device web management interfaces that expose version strings or default page titles, identifying all websites using a specific technology, or tracking malicious code distribution.",
        "description_zh_tw": "PublicWWW 索引數十億個網站的源代碼，允許按 HTML 片段、JavaScript 庫、meta 標籤、追蹤 ID 或技術指紋搜尋，可用於查找暴露版本字符串或默認頁面標題的 IoT 設備網絡管理界面、識別使用特定技術的所有網站或追蹤惡意代碼分佈。",
        "use_cases": [
            "Search for all websites exposing a specific IoT device admin panel by its default page title",
            "Find all sites using a specific JavaScript tracking ID to map an entity's web infrastructure",
            "Identify websites sharing a specific code snippet to detect malicious injection campaigns"
        ],
        "tags": ["iot-osint", "source-code-search", "fingerprinting", "web-intelligence"],
        "pricing": "freemium",
        "difficulty": "intermediate",
        "target_types": ["domain", "network"],
        "platforms": ["web"],
        "ethical_flag": False,
        "ethics_note": None,
        "source_section": "IoT & Smart Devices",
        "source_permalink": "https://publicwww.com/",
        "review": REV,
        "curation_status": "curated",
        "curation_reason": "Unique source-code fingerprint search with no direct equivalent; strong IoT panel detection.",
        "maintenance_status": "active",
        "last_verified_at": "2026-05-08T00:00:00Z",
        "is_dead_link": False, "is_active": True,
    },
]

# ── Load, merge, validate, save ─────────────────────────────────────────────
with TOOLS_FILE.open() as f:
    existing = json.load(f)

existing_ids   = {t["id"] for t in existing}
existing_names = {t["name"].lower() for t in existing}

added, skipped = [], []
for tool in NEW_TOOLS:
    if tool["id"] in existing_ids:
        skipped.append(f"SKIP (dup id)  {tool['id']}")
        continue
    if tool["name"].lower() in existing_names:
        skipped.append(f"SKIP (dup name) {tool['name']}")
        continue
    existing.append(tool)
    added.append(tool["name"])

with TOOLS_FILE.open("w") as f:
    json.dump(existing, f, indent=2, ensure_ascii=False)

print(f"\n{'─'*60}")
print(f"  Added   : {len(added)}")
print(f"  Skipped : {len(skipped)}")
print(f"  Total   : {len(existing)}")
print(f"{'─'*60}")
for n in added:
    print(f"  + {n}")
if skipped:
    print()
    for s in skipped:
        print(f"  {s}")
print()
